Add xvfb configuration and downloading gurobi license to setup script

diff --git a/setup/mac/install_prereqs b/setup/mac/install_prereqs
--- a/setup/mac/install_prereqs
+++ b/setup/mac/install_prereqs
@@ -32,16 +32,21 @@
 
 set -euxo pipefail
 
+if [[ -z "${WORKSPACE-}" ]]; then
+  echo 'ERROR: This script must be run on a Jenkins node' >&2
+  exit 1
+fi
+
 if [[ "${EUID}" -eq 0 ]]; then
   echo 'ERROR: This script must NOT be run as root' >&2
-  exit 1
+  exit 2
 fi
 
 if ! command -v brew &>/dev/null; then
   /usr/bin/ruby -e "$(curl --fail --location --retry 4 --show-error --silent https://raw.githubusercontent.com/Homebrew/install/master/install)"
 fi
 
-[[ -z "${TERM}" ]] || export HOMEBREW_COLOR=1
+[[ -z "${TERM-}" ]] || export HOMEBREW_COLOR=1
 
 export HOMEBREW_CURL_RETRIES=4
 
diff --git a/setup/ubuntu/install_prereqs b/setup/ubuntu/install_prereqs
--- a/setup/ubuntu/install_prereqs
+++ b/setup/ubuntu/install_prereqs
@@ -32,10 +32,20 @@
 
 set -euxo pipefail
 
-if [[ "${EUID}" -ne 0 ]]; then
-  echo 'ERROR: This script must be run as root' >&2
+env
+
+if [[ -z "${WORKSPACE-}" ]]; then
+  echo 'ERROR: This script must be run on a Jenkins node' >&2
   exit 1
 fi
+
+if [[ "${EUID}" -ne 0 ]]; then
+  echo 'ERROR: This script must be run as root' >&2
+  exit 2
+fi
+
+systemctl disable apt-daily.service
+systemctl disable apt-daily.timer
 
 echo 'APT::Acquire::Retries "4";' | tee /etc/apt/apt.conf.d/80-acquire-retries
 
@@ -43,6 +53,8 @@ export DEBIAN_FRONTEND=noninteractive
 
 apt-get update --quiet --quiet
 trap 'rm --force --recursive /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin /var/lib/apt/lists/*' EXIT
+
+apt-get purge --assume-yes --option Dpkg::Use-Pty=0 --quiet unattended-upgrades
 
 apt-get install --assume-yes --no-install-recommends --option Dpkg::Use-Pty=0 --quiet \
   apt-transport-https \
@@ -55,6 +67,19 @@ apt-get install --assume-yes --no-install-recommends --option Dpkg::Use-Pty=0 --
   openjdk-8-jdk-headless \
   wget \
   xvfb
+
+cat << 'EOF' > /lib/systemd/system/xvfb.service
+[Unit]
+After=network.target
+
+[Service]
+ExecStart=/usr/bin/Xvfb :99 -screen 0 1280x1024x24 -ac +extension GLX +extension RANDR +render -noreset
+
+[Install]
+WantedBy=multi-user.target
+EOF
+
+systemctl --now enable /lib/systemd/system/xvfb.service
 
 wget --no-verbose --output-document - https://apt.kitware.com/keys/kitware-archive-latest.asc | APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 apt-key add -
 echo "deb https://apt.kitware.com/ubuntu/ $(lsb_release --codename --short) main" | tee /etc/apt/sources.list.d/kitware.list
@@ -70,4 +95,6 @@ wget --no-verbose --output-document /tmp/gurobi8.0.1_linux64.tar.gz https://pack
 echo '28c028b8708869c27a93edc2769b645db4906dc7c80a4d283ed6db672b587478  /tmp/gurobi8.0.1_linux64.tar.gz' | shasum --algorithm 256 --check -
 trap 'rm --force --recursive /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin /var/lib/apt/lists/* /tmp/gurobi8.0.1_linux64.tar.gz' EXIT
 tar --extract --file /tmp/gurobi8.0.1_linux64.tar.gz --directory /opt
+aws s3 cp --quiet s3://drake-provisioning/gurobi/gurobi.lic /opt/gurobi801/gurobi.lic
+echo '85a76935617e809af43275fa4d7f7fc38182973c5756edde9b8db59ef65420cb  /opt/gurobi801/gurobi.lic' | shasum --algorithm 256 --check -
 chown --recursive root:root /opt/gurobi801
