Restructure macOS provisioning workflow (#371)
Instead of copying the provisioning script to the image, which then
clones this repo, have the maintainer clone this repo and run the
script. This facilitates running branches of provisioning scripts
(commonly needed when updating prerequisites), and generally removes
some awkwardness left over from automating this workflow.

diff --git a/setup/mac/provision_image b/setup/mac/provision_image
--- a/setup/mac/provision_image
+++ b/setup/mac/provision_image
@@ -31,39 +31,63 @@
 # OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 # OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-# This script is expected to only be used in the creation of provisioned images
-# NOT during normal CI setup
+# This script is intended for use by maintainers in the creation of provisioned
+# images, not during regular CI workflows which run on every job. See README.md
+# for usage details.
 
-# TODO(tyler-yankee): Update this workflow so that the maintainer creating
-# the provisioned image clones drake-ci and then calls this script (or
-# install_prereqs directly), rather than them copying this script which clones
-# drake-ci/main. The current workflow is an artifact of a prior state lacking
-# the automation we have today, and aside from just being awkward, it notably
-# doesn't allow checking out a branch of drake-ci to provision (without manually
-# modifying the file).
-# The modified script could clone drake to install its prereqs, defaulting to
-# master but allowing a branch name as argument.
+set -euxo pipefail
 
-# Update Homebrew packages.
-brew update
+cleanup () {
+  rm -rf "${drake_root}"
+
+  brew cleanup --prune=all
+  rm -rf "$(brew --cache)"
+  rm -rf "${HOME}/Library/Logs/Homebrew/*"
+
+  # Update this version of pip as Drake updates its supported Python versions.
+  pip3.14 cache purge
+}
+
+if [[ "${EUID}" -eq 0 ]]; then
+  echo 'ERROR: This script must NOT be run as root' >&2
+  exit 2
+fi
+
+readonly setup_mac_dir="$(dirname "${BASH_SOURCE}")"
+readonly drake_root="$(mktemp -d -t drake-ci-provisioning)"
+
+trap 'cleanup' EXIT
+
+[[ -z "${TERM-}" ]] || export HOMEBREW_COLOR=1
+
+export HOMEBREW_CASK_OPTS=--require-sha
+export HOMEBREW_CURL_RETRIES=4
+export HOMEBREW_NO_AUTO_UPDATE=1
+export HOMEBREW_NO_INSECURE_REDIRECT=1
+export HOMEBREW_NO_INSTALL_CLEANUP=1
+
+brew analytics off
+brew update || (sleep 15; brew update)
 brew upgrade
+
+readonly gurobi_1203_pkg='/tmp/gurobi12.0.3_macos_universal2.pkg'
+curl --retry 4 -o $gurobi_1203_pkg \
+  https://packages.gurobi.com/12.0/$(basename $gurobi_1203_pkg)
+echo "e1e771e9cf8aa7882b1cdc000be91c2b5fadd18f3fcdd00f2824dd207be09613  $gurobi_1203_pkg" \
+  | sha256sum -c -
+sudo /usr/sbin/installer -pkg $gurobi_1203_pkg -target /
 
 # Install Java, to be used for Jenkins. The version must be the same as the one
 # used by Jenkins.
 brew install --cask temurin@21
 
-# Install the tools that drake-ci does.
-git clone --depth 1 https://github.com/RobotLocomotion/drake-ci.git
-# WORKSPACE=setup is a bypass that allows the script to run (which requires
-# that it be defined, as Jenkins always does).
-WORKSPACE=setup ./drake-ci/setup/mac/install_prereqs
-
-# Install the tools that drake does.
-git clone --depth 1 https://github.com/RobotLocomotion/drake.git
-./drake/setup/mac/install_prereqs.sh --developer
-
-# Clean up.
-brew cleanup --prune=all
-# Update this version of pip as Drake updates its supported Python versions.
-pip3.14 cache purge
-rm -rf drake drake-ci
+# Install Drake's prerequisites.
+git clone https://github.com/RobotLocomotion/drake.git \
+    --depth 1 "${drake_root}"
+readonly drake_setup_script="${drake_root}/setup/mac/install_prereqs.sh"
+if [[ ! -f "${drake_setup_script}" ]]; then
+  echo "drake setup script not found; expected: ${drake_setup_script}" >&2
+  exit 1
+fi
+# Use `--developer` to install the prereqs for building wheels.
+"${drake_setup_script}" --developer
