Restructure macOS provisioning workflow
Instead of copying the script to the image and the script cloning this
repo, have the maintainer clone this repo and run the script. This
facilitates running branches of provisioning scripts (commonly needed
when updating prerequisites), and generally removes some awkwardness
leftover from automating this workflow.

diff --git a/setup/mac/provision_image b/setup/mac/provision_image
--- a/setup/mac/provision_image
+++ b/setup/mac/provision_image
@@ -34,36 +34,28 @@
 # This script is expected to only be used in the creation of provisioned images
 # NOT during normal CI setup
 
-# TODO(tyler-yankee): Update this workflow so that the maintainer creating
-# the provisioned image clones drake-ci and then calls this script (or
-# install_prereqs directly), rather than them copying this script which clones
-# drake-ci/main. The current workflow is an artifact of a prior state lacking
-# the automation we have today, and aside from just being awkward, it notably
-# doesn't allow checking out a branch of drake-ci to provision (without manually
-# modifying the file).
-# The modified script could clone drake to install its prereqs, defaulting to
-# master but allowing a branch name as argument.
+set -euxo pipefail
 
-# Update Homebrew packages.
-brew update
-brew upgrade
+readonly setup_mac_dir="$(dirname "${BASH_SOURCE}")"
+readonly ci_root="$(git rev-parse --show-toplevel)"
+readonly drake_root="$(realpath "${ci_root}/../drake")"
 
-# Install Java, to be used for Jenkins. The version must be the same as the one
-# used by Jenkins.
-brew install --cask temurin@21
-
-# Install the tools that drake-ci does.
-git clone --depth 1 https://github.com/RobotLocomotion/drake-ci.git
 # WORKSPACE=setup is a bypass that allows the script to run (which requires
 # that it be defined, as Jenkins always does).
-WORKSPACE=setup ./drake-ci/setup/mac/install_prereqs
+WORKSPACE=setup "$setup_mac_dir/install_prereqs"
 
-# Install the tools that drake does.
-git clone --depth 1 https://github.com/RobotLocomotion/drake.git
-./drake/setup/mac/install_prereqs.sh --developer
+# Install the tools that drake does, with `--developer` to install the prereqs
+# needed for building wheels.
+git clone --depth 1 https://github.com/RobotLocomotion/drake.git "$drake_root"
+readonly drake_setup_script="$drake_root/setup/mac/install_prereqs.sh"
+if [[ ! -f "$drake_setup_script" ]]; then
+  echo "drake setup script not found; expected: $drake_setup_script" >&2
+  exit 1
+fi
+"$drake_setup_script" --developer
 
 # Clean up.
 brew cleanup --prune=all
 # Update this version of pip as Drake updates its supported Python versions.
 pip3.14 cache purge
-rm -rf drake drake-ci
+rm -rf "$ci_root" "$drake_root"
